P0:
  evolve:
    w_positive: 2
    w_negative: 0
    w_neutral: 1
    beta_select:
      alpha: 2
      beta: 2
  snp:
    gamma_pos:
      shape: 20
      rate: 1
    beta_prop:
      alpha: 2
      beta: 2
  indel:
    gamma_pos:
      shape: 10
      rate: 1
    bernouilli:
      p: 0.5
    weights: [1, 1, 5]
    beta_prop:
      alpha: 2
      beta: 2
  deletion:
    gamma_pos:
      shape: 1
      rate: 10
    gamma_size:
      shape: 5
      rate: 2
    beta_prop:
      alpha: 2
      beta: 2

P1:
  evolve:
    w_positive: 2
    w_negative: 0
    w_neutral: 1
    beta_select:
      alpha: 2
      beta: 2
  snp:
    gamma_pos:
      shape: 5
      rate: 1
    beta_prop:
      alpha: 2
      beta: 2
  indel:
    gamma_pos:
      shape: 2
      rate: 1
    bernouilli:
      p: 0.5
    weights: [1, 1, 5]
    beta_prop:
      alpha: 2
      beta: 2
  deletion:
    gamma_pos:
      shape: 1
      rate: 10
    gamma_size:
      shape: 4
      rate: 2
    beta_prop:
      alpha: 2
      beta: 2

P2:
  evolve:
    w_positive: 2
    w_negative: 0
    w_neutral: 1
    beta_select:
      alpha: 2
      beta: 2
  snp:
    gamma_pos:
      shape: 5
      rate: 1
    beta_prop:
      alpha: 2
      beta: 2
  indel:
    gamma_pos:
      shape: 2
      rate: 1
    bernouilli:
      p: 0.5
    weights: [1, 1, 5]
    beta_prop:
      alpha: 2
      beta: 2
  deletion:
    gamma_pos:
      shape: 1
      rate: 10
    gamma_size:
      shape: 4
      rate: 2
    beta_prop:
      alpha: 2
      beta: 2

P3:
  evolve:
    w_positive: 2
    w_negative: 0
    w_neutral: 1
    beta_select:
      alpha: 2
      beta: 2
  snp:
    gamma_pos:
      shape: 5
      rate: 1
    beta_prop:
      alpha: 2
      beta: 2
  indel:
    gamma_pos:
      shape: 2
      rate: 1
    bernouilli:
      p: 0.5
    weights: [1, 1, 5]
    beta_prop:
      alpha: 2
      beta: 2
  deletion:
    gamma_pos:
      shape: 1
      rate: 10
    gamma_size:
      shape: 4
      rate: 2
    beta_prop:
      alpha: 2
      beta: 2